spring:
  application:
    name: api

  security:
    user:
      name: user
      password: user
    auth:
      secret: abc123
      issuer: my-auth

  datasource:
    url: jdbc:postgresql://webflux-postgres:5432/api-performance
    driverClassName: org.postgresql.Driver
    username: user
    password: user@123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework: ERROR
    org.springframework.web: ERROR
    org.hibernate: ERROR
    root: ERROR

server:
  tomcat:
    threads:
      max: 10